%bcond_without tests
%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/rolling/.*$
%global __requires_exclude_from ^/opt/ros/rolling/.*$

Name:           ros-rolling-rmf-building-sim-gazebo-plugins
Version:        1.2.0
Release:        2%{?dist}%{?release_suffix}
Summary:        ROS rmf_building_sim_gazebo_plugins package

License:        Apache 2.0
Source0:        %{name}-%{version}.tar.gz

Requires:       opencv-devel
Requires:       qt5-qtbase
Requires:       qt5-qtbase-devel
Requires:       ros-rolling-gazebo-dev
Requires:       ros-rolling-gazebo-ros
Requires:       ros-rolling-menge-vendor
Requires:       ros-rolling-rclcpp
Requires:       ros-rolling-rmf-building-sim-common
Requires:       ros-rolling-rmf-fleet-msgs
Requires:       ros-rolling-ros-workspace
BuildRequires:  opencv-devel
BuildRequires:  qt5-qtbase
BuildRequires:  qt5-qtbase-devel
BuildRequires:  ros-rolling-ament-cmake
BuildRequires:  ros-rolling-gazebo-dev
BuildRequires:  ros-rolling-gazebo-ros
BuildRequires:  ros-rolling-menge-vendor
BuildRequires:  ros-rolling-rclcpp
BuildRequires:  ros-rolling-rmf-building-sim-common
BuildRequires:  ros-rolling-rmf-fleet-msgs
BuildRequires:  ros-rolling-ros-workspace
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%description
Gazebo plugins so that buildings generated by rmf_building_map_tools can talk to
the ROS 2-based systems in the rmf_core package.

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/rolling/setup.sh" ]; then . "/opt/ros/rolling/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/rolling" \
    -DAMENT_PREFIX_PATH="/opt/ros/rolling" \
    -DCMAKE_PREFIX_PATH="/opt/ros/rolling" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/rolling/setup.sh" ]; then . "/opt/ros/rolling/setup.sh"; fi
%make_install -C obj-%{_target_platform}

%if 0%{?with_tests}
%check
# Look for a Makefile target with a name indicating that it runs tests
TEST_TARGET=$(%__make -qp -C obj-%{_target_platform} | sed "s/^\(test\|check\):.*/\\1/;t f;d;:f;q0")
if [ -n "$TEST_TARGET" ]; then
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/rolling/setup.sh" ]; then . "/opt/ros/rolling/setup.sh"; fi
CTEST_OUTPUT_ON_FAILURE=1 \
    %make_build -C obj-%{_target_platform} $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif

%files
/opt/ros/rolling

%changelog
* Mon Jul 12 2021 Morgan Quigley <morgan@openrobotics.org> - 1.2.0-2
- Autogenerated by Bloom

* Wed Jul 07 2021 Morgan Quigley <morgan@openrobotics.org> - 1.2.0-1
- Autogenerated by Bloom

