%bcond_without tests
%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/rolling/.*$
%global __requires_exclude_from ^/opt/ros/rolling/.*$

Name:           ros-rolling-rmf-robot-sim-gz-plugins
Version:        2.4.0
Release:        1%{?dist}%{?release_suffix}
Summary:        ROS rmf_robot_sim_gz_plugins package

License:        Apache 2.0
Source0:        %{name}-%{version}.tar.gz

Requires:       eigen3-devel
Requires:       qt5-qtbase
Requires:       qt5-qtdeclarative
Requires:       ros-rolling-gz-gui-vendor
Requires:       ros-rolling-gz-msgs-vendor
Requires:       ros-rolling-gz-plugin-vendor
Requires:       ros-rolling-gz-rendering-vendor
Requires:       ros-rolling-gz-sim-vendor
Requires:       ros-rolling-gz-transport-vendor
Requires:       ros-rolling-rclcpp
Requires:       ros-rolling-rmf-building-map-msgs
Requires:       ros-rolling-rmf-building-sim-gz-plugins
Requires:       ros-rolling-rmf-fleet-msgs
Requires:       ros-rolling-rmf-robot-sim-common
Requires:       ros-rolling-ros-workspace
BuildRequires:  eigen3-devel
BuildRequires:  qt5-qtbase
BuildRequires:  qt5-qtdeclarative
BuildRequires:  ros-rolling-ament-cmake
BuildRequires:  ros-rolling-gz-gui-vendor
BuildRequires:  ros-rolling-gz-msgs-vendor
BuildRequires:  ros-rolling-gz-plugin-vendor
BuildRequires:  ros-rolling-gz-rendering-vendor
BuildRequires:  ros-rolling-gz-sim-vendor
BuildRequires:  ros-rolling-gz-transport-vendor
BuildRequires:  ros-rolling-rclcpp
BuildRequires:  ros-rolling-rmf-building-map-msgs
BuildRequires:  ros-rolling-rmf-building-sim-gz-plugins
BuildRequires:  ros-rolling-rmf-fleet-msgs
BuildRequires:  ros-rolling-rmf-robot-sim-common
BuildRequires:  ros-rolling-ros-workspace
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%description
ROS 2 Gazebo plugins for TeleportIngestors and TeleportDispensers

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/rolling/setup.sh" ]; then . "/opt/ros/rolling/setup.sh"; fi
mkdir -p .obj-%{_target_platform} && cd .obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/rolling" \
    -DAMENT_PREFIX_PATH="/opt/ros/rolling" \
    -DCMAKE_PREFIX_PATH="/opt/ros/rolling" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
%if !0%{?with_tests}
    -DBUILD_TESTING=OFF \
%endif
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/rolling/setup.sh" ]; then . "/opt/ros/rolling/setup.sh"; fi
%make_install -C .obj-%{_target_platform}

%if 0%{?with_tests}
%check
# Look for a Makefile target with a name indicating that it runs tests
TEST_TARGET=$(%__make -qp -C .obj-%{_target_platform} | sed "s/^\(test\|check\):.*/\\1/;t f;d;:f;q0")
if [ -n "$TEST_TARGET" ]; then
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/rolling/setup.sh" ]; then . "/opt/ros/rolling/setup.sh"; fi
CTEST_OUTPUT_ON_FAILURE=1 \
    %make_build -C .obj-%{_target_platform} $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif

%files
/opt/ros/rolling

%changelog
* Sat Jun 15 2024 Luca Della Vedova <luca@openrobotics.org> - 2.4.0-1
- Autogenerated by Bloom

* Wed Jun 12 2024 Luca Della Vedova <luca@openrobotics.org> - 2.3.1-1
- Autogenerated by Bloom

